import type { AgentModule } from "../core/module";

/**
 * PatchGenerator Module
 *
 * Subscribes to evolution.analysis.requested
 * Uses LLM to analyze failures and generate patches
 * Publishes evolution.patch.proposed
 */
export const PatchGeneratorModule: AgentModule = {
  name: "patch-generator",

  start(ctx) {
    ctx.bus.subscribe("evolution.analysis.requested", async (event) => {
      const { failureEventId } = event.payload;

      console.log(`[patch-generator] Generating patch for failure: ${failureEventId}`);

      try {
        // Use LLM to generate a patch
        const response = await ctx.llm.chat({
          taskType: "patch_generate",
          messages: [
            {
              role: "system",
              content: `You are an automated patch generator for a self-healing agent system.
When a failure occurs, you analyze the failure details and generate a patch in JSON format.
The patch should include:
- reason: A brief description of why the patch is needed
- risk: "low", "medium", or "high"
- changes: Array of file changes, each with path, operation ("replace_file"), and content

Respond ONLY with valid JSON, no markdown code fences.`
            },
            {
              role: "user",
              content: `Generate a patch for the following failure event ID: ${failureEventId}

The failure was detected by the self-healing system. Analyze the failure and propose a minimal, safe patch.
Focus on the most likely root cause and the smallest possible fix.

Respond with JSON in this format:
{
  "reason": "Brief description of the fix",
  "risk": "low",
  "changes": [
    {
      "path": "path/to/file",
      "operation": "replace_file",
      "content": "New file content"
    }
  ]
}`
            }
          ]
        });

        // Parse the LLM response as JSON
        let patch;
        try {
          const content = response.content
            .replace(/```json\n?/g, "")
            .replace(/```\n?/g, "")
            .trim();
          patch = JSON.parse(content);
        } catch {
          // If LLM response is not valid JSON, create a structured patch from the text
          patch = {
            reason: response.content.substring(0, 200),
            risk: "low",
            changes: [
              {
                path: "src/modules/agent-runtime.ts",
                operation: "replace_file" as const,
                content: `// Patch generated by LLM (${response.modelName})\n// ${response.content.substring(0, 500)}`
              }
            ]
          };
        }

        // Publish LLM completion event
        await ctx.bus.publish({
          type: "llm.chat.completed",
          source: "patch-generator",
          correlationId: event.correlationId,
          causationId: event.id,
          payload: {
            taskType: "patch_generate",
            modelId: response.modelId,
            modelName: response.modelName,
            provider: response.provider,
            content: response.content.substring(0, 200),
            durationMs: response.durationMs,
            tokensUsed: response.usage?.totalTokens,
            fallbackUsed: response.fallbackUsed
          }
        });

        // Propose the patch
        await ctx.bus.publish({
          type: "evolution.patch.proposed",
          source: "patch-generator",
          correlationId: event.correlationId,
          causationId: event.id,
          payload: patch
        });
      } catch (error) {
        console.error("[patch-generator] LLM call failed, using fallback:", error);

        // Fallback to hardcoded patch if LLM fails
        const patch = {
          reason: "Fix empty message causing runtime_error (fallback patch)",
          risk: "low",
          changes: [
            {
              path: "src/modules/agent-runtime.ts",
              operation: "replace_file" as const,
              content: "// New full file content — generated by fallback patch generator"
            }
          ]
        };

        await ctx.bus.publish({
          type: "evolution.patch.proposed",
          source: "patch-generator",
          correlationId: event.correlationId,
          causationId: event.id,
          payload: patch
        });
      }
    });
  }
};
