/**
 * Fallback Provider — Mock LLM provider for testing and offline mode
 *
 * Returns predefined responses based on task type.
 * Used when no real LLM provider is available.
 */

import type { LLMProvider, LLMChatMessage } from "../types";

const TASK_RESPONSES: Record<string, string> = {
  chat: "I'm OpenEvolve, an event-driven self-evolving agent. How can I help you today?",
  patch_generate: `// Patch generated by OpenEvolve\n// Reason: Fix identified issue based on failure analysis\n{\n  "reason": "Auto-generated patch for detected failure",\n  "risk": "low",\n  "changes": []\n}`,
  feature_analyze: JSON.stringify({
    analysis: "This feature appears useful for extending agent capabilities.",
    usefulness: 0.7,
    frequency: 0.6,
    integration: 0.5,
    security: 0.7,
    maintenance: 0.6,
    novelty: 0.5,
    overlap: 0.3,
  }),
  spec_generate: JSON.stringify({
    id: "spec-fallback",
    type: "plugin",
    description: "Auto-generated specification from fallback provider",
    permissions: { network: { allow: [] }, filesystem: { read: [], write: [] } },
    events: { subscribes: [], publishes: [] },
    riskLevel: "low",
    evals: ["Can be loaded without errors"],
    installLevel: 1,
  }),
  prototype_build: `// Auto-generated plugin prototype\nexport default {\n  name: "fallback-plugin",\n  version: "0.1.0",\n  setup(ctx) {\n    console.log("Fallback plugin loaded");\n  }\n};`,
  code_review: "Code review completed. No critical issues found. Suggestions: Consider adding error handling and input validation.",
  summarize: "Summary: The analyzed content describes an event-driven self-evolving agent system with multiple evolution chains.",
  embedding: "",
};

export class FallbackProvider implements LLMProvider {
  readonly type = "custom" as const;

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async chat(request: {
    model: string;
    messages: LLMChatMessage[];
    maxTokens?: number;
    temperature?: number;
    topP?: number;
    apiKey?: string;
    baseUrl?: string;
    tools?: any[];
    tool_choice?: any;
  }): Promise<{
    content: string;
    toolCalls?: any[];
    usage?: { promptTokens: number; completionTokens: number; totalTokens: number };
  }> {
    // Try to infer task type from system message
    const systemMsg = request.messages.find((m) => m.role === "system");
    let taskType: string = "chat";

    if (systemMsg && systemMsg.content) {
      const content = systemMsg.content.toLowerCase();
      if (content.includes("patch") || content.includes("repair")) {
        taskType = "patch_generate";
      } else if (content.includes("feature") && content.includes("analyz")) {
        taskType = "feature_analyze";
      } else if (content.includes("spec")) {
        taskType = "spec_generate";
      } else if (content.includes("prototype")) {
        taskType = "prototype_build";
      } else if (content.includes("review")) {
        taskType = "code_review";
      } else if (content.includes("summar")) {
        taskType = "summarize";
      }
    }

    // If there's a user message, use it to generate a contextual response
    const userMsg = request.messages.find((m) => m.role === "user");
    const baseResponse = TASK_RESPONSES[taskType] ?? TASK_RESPONSES.chat!;

    const content = (userMsg?.content)
      ? `[Fallback Provider] In response to: "${String(userMsg.content).substring(0, 80)}"\n\n${baseResponse}`
      : baseResponse;

    // Simulate token usage
    const promptTokens = request.messages.reduce(
      (sum, m) => sum + Math.ceil((m.content?.length ?? 0) / 4),
      0
    );
    const completionTokens = Math.ceil(content.length / 4);

    return {
      content,
      toolCalls: undefined,
      usage: {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      },
    };
  }
}
